environment: development

image:
  repository: asia.gcr.io/staging-host-12358/silent-assassin
  tag: "latest"
  pullPolicy: Always 

resources:
  enabled: false

hpa:
  enabled: false

workloadIdentityServiceAccount:
  enabled: true
  name: "silent-assassin@development-backend-12358.iam.gserviceaccount.com"