environment: production

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: component
          operator: In
          values:
          - "admin"
        - key: active
          operator: In
          values:
          - "true"

workloadIdentityServiceAccount:
  enabled: true
  name: "silent-assassin@production-backend-12358.iam.gserviceaccount.com"