# This is a YAML-formatted file.
# Declare variables to be passed into your templates.]
version: 1.0
replicaCount: 1
revisionHistoryLimit: 4
containerPort: 8080
imageConfig:
  pullPolicy: Always
  image: rapidolabs/silent-assassin:1.0.0

resources:
  enabled: true
  requests:
    cpu: 20m
    memory: 20Mi
  limits:
    cpu: 100m
    memory: 100Mi

service:
  type: ClusterIP
  servicePort: 80

# when using workload identity set this to the Google Cloud Service Account
workloadIdentityServiceAccount:
  enabled: true
  name: ""

secret:
  # if set to true the values are already base64 encoded when provided, otherwise the template performs the base64 encoding
  # this value will be ignored if workloadIdentityServiceAccount is enabled.
  valuesAreBase64Encoded: false

  # sets a json keyfile for a gcp service account
  # this value will be ignored if workloadIdentityServiceAccount is enabled.
  googleServiceAccountKeyfileJson: '{"type": "service_account"}'

silent_assassin:
  node_selectors: "cloud.google.com/gke-preemptible=true"
  # debug | info | warn | error
  logger_level: "info"
  # InCluster | OutCluster
  k8s_run_mode: InCluster
  spotter:
    poll_interval_ms: 1000
    white_list_interval_hours: "06:30-08:30,18:30-00:30"
  killer:
    poll_interval_ms: 1000
    draining_timeout_when_node_expired_ms: 300000
    draining_timeout_when_node_preempted_ms: 25000
  slack:
    webhook_url: ""
    username: "SILENT-ASSASSIN"
    channel: ""
    SLACK_ICON_URL: ""
  client:
    server_retries: 4
    watch_maintainance_event: true
