SPOTTER:
  POLL_INTERVAL_MS: {{key "rapido/silent-assassin/svc/spotter.poll_interval_ms"}}
  LABEL_SELECTORS: {{key "rapido/silent-assassin/svc/spotter.label-selectors"}}
  WHITE_LIST_INTERVAL_HOURS: {{key "rapido/silent-assassin/svc/spotter.white_list_interval_hours"}}

KILLER:
  POLL_INTERVAL_MS: {{key "rapido/silent-assassin/svc/killer_poll_interval_ms"}}
  DRAINING_TIMEOUT_MS: {{key "rapido/silent-assassin/svc/killer_draining_timeout_ms"}}

LOGGER:
  LEVEL: {{key "rapido/silent-assassin/svc/logger_level"}} # debug | info | warn | error

KUBERNETES:
  RUN_MODE: {{key "rapido/silent-assassin/svc/kubernetes_run_mode"}} # InCluster | OutCluster

SLACK:
  WEBHOOK_URL: {{key "rapido/silent-assassin/svc/slack_webhook_url"}}
  USERNAME: {{key "rapido/silent-assassin/svc/slack_username"}}
  CHANNEL: {{key "rapido/silent-assassin/svc/slack_channel"}}
  SLACK_ICON_URL: {{key "rapido/silent-assassin/svc/slack_slack_icon_url"}}