SERVER_HOST: "http://silent-assassin.andromeda.svc.cluster.local"
SPOTTER:
  POLL_INTERVAL_MS: 1000
  LABEL_SELECTORS: "cloud.google.com/gke-preemptible=true,component=services"
  WHITE_LIST_INTERVAL_HOURS: "06:30-08:30,18:30-00:30"

KILLER:
  POLL_INTERVAL_MS: 1000
  DRAINING_TIMEOUT_MS: 300000
  PREEMPTION_TIMEOUT_MS: 25000

LOGGER:
  LEVEL: debug # debug | info | warn | error

KUBERNETES:
  RUN_MODE: OutCluster # InCluster | OutCluster

SLACK:
  WEBHOOK_URL: "https://hooks.slack.com/services/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"
  USERNAME: "SILENT ASSASSIN"
  CHANNEL: "test-slack-to-be-deleted-soon"
  SLACK_ICON_URL: "https://avatars.slack-edge.com/2019-11-12/831618011008_5c3d2e53846f843edc54_512.png"

CLIENT:
  SERVER_RETRIES: 4
  WATCH_MAINTAINANCE_EVENTS: "true"