{{- if .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  labels: 
    team: {{ .Values.team }}
spec:
  hosts:
  - {{ .Chart.Name }}.svc.{{ .Values.environment }}.internal
  - {{ .Chart.Name }}
  - {{ .Chart.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  gateways:
  {{- range $index, $gateway := .Values.istio.ingressGateway }}
  - {{ $gateway }}
  {{- end }}
  http:
  - route:
    - destination:
        host: {{ .Chart.Name }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.servicePort }}
{{ end }}