apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-client
  labels:
    chart: {{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Release.Name }}
    team: {{ .Values.team }}
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-client"
      version: {{ .Values.version | quote }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-client"
        version: {{ .Values.version | quote }}
        team: {{ .Values.team }}
    spec:
      # Necessary to hit the node's metadata server when using Workload Identity
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ .Release.Name }}
      initContainers:
        - name: install
          image: hashicorp/consul-template:0.20.0-alpine
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: token
          args:
            - "-consul-addr"
            - "{{ .Values.consul.host}}:{{ .Values.consul.port}}"
            - "-vault-addr"
            - "{{.Values.vault.host}}:{{.Values.vault.port}}"
            - "-template"
            - "/usr/app/templates/application.yaml:/layers/golang/app/config/application.yaml"
            - "-once"
            - "-log-level=trace"
          volumeMounts:
            - mountPath: /usr/app/templates
              name: config-template-volume
            - mountPath: /layers/golang/app/config
              name: config-pv-volume
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          command: ["/bin/sh"]
          args: ["-c", "cd /layers/golang/app/; ./silent-assassin start client"]
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
          {{- if .Values.daemonset.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.daemonset.livenessProbe.path }}
              port: {{ .Values.daemonset.containerPort }}
            initialDelaySeconds: {{ .Values.daemonset.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.daemonset.livenessProbe.periodSeconds}}
          {{- end }}
          {{- if .Values.daemonset.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.daemonset.readinessProbe.path }}
              port: {{ .Values.daemonset.containerPort }}
            initialDelaySeconds: {{ .Values.daemonset.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.daemonset.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.daemonset.resources }}
          resources:
            requests:
              cpu: {{ .Values.daemonset.resources.requests.cpu }}
              memory: {{ .Values.daemonset.resources.requests.memory }}
            limits:
              cpu: {{ .Values.daemonset.resources.limits.cpu }}
              memory: {{ .Values.daemonset.resources.limits.memory }}
          {{- end }}
          env:
            - name: RAPIDO_ENV
              value: {{ .Values.environment }}
            {{- if not .Values.workloadIdentityServiceAccount.enabled }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /gcp-service-account/service-account-key.json
            {{- end }}
          volumeMounts:
            - mountPath: /layers/golang/app/config
              name: config-pv-volume
          {{- if not .Values.workloadIdentityServiceAccount.enabled }}
            - name: gcp-service-account-secret
              mountPath: /gcp-service-account
          {{- end }}
      volumes:
        - name: config-pv-volume
          emptyDir: {}
        - name: config-template-volume
          configMap:
            name: {{ .Release.Name }}-config
        {{- if not .Values.workloadIdentityServiceAccount.enabled }}
        - name: gcp-service-account-secret
          secret:
            secretName: {{ .Release.Name }}
        {{- end }}
      nodeSelector:
        "cloud.google.com/gke-preemptible": "true"
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule