apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
      version: {{ .Values.version | quote }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: {{ .Values.version | quote }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.imageConfig.image }}
          command: ["/bin/sh"]
          args: ["-c", "cd /layers/golang/app/; ./silent-assassin start server"]
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
              protocol: TCP
          {{- if .Values.resources }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          {{- end }}
          env:
            {{- if not .Values.workloadIdentityServiceAccount.enabled }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /gcp-service-account/service-account-key.json
            {{- end }}
          volumeMounts:
            - mountPath: /layers/golang/app/config
              name: configuration
          {{- if not .Values.workloadIdentityServiceAccount.enabled }}
            - name: gcp-service-account-secret
              mountPath: /gcp-service-account
          {{- end }}
      volumes:
        - name: configuration
          configMap:
            name: {{ .Release.Name }}-config
        {{- if not .Values.workloadIdentityServiceAccount.enabled }}
        - name: gcp-service-account-secret
          secret:
            secretName: {{ .Release.Name }}
        {{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
