apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Chart.Name }}
    team: {{ .Values.team }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}
      version: {{ .Values.version | quote }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.version | quote }}
        team: {{ .Values.team }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      initContainers:
        - name: install
          image: hashicorp/consul-template:0.20.0-alpine
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: token
          args:
            - "-consul-addr"
            - "{{ .Values.consul.host}}:{{ .Values.consul.port}}"
            - "-vault-addr"
            - "{{.Values.vault.host}}:{{.Values.vault.port}}"
            - "-template"
            - "/usr/app/templates/application.yaml:/usr/app/config/.silent-assassin.yaml"
            - "-once"
            - "-log-level=trace"
          volumeMounts:
            - mountPath: /usr/app/templates
              name: config-template-volume
            - mountPath: /usr/app/config
              name: config-pv-volume
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
              protocol: TCP
          {{- if .Values.resources }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          {{- end }}
          env:
            - name: RAPIDO_ENV
              value: {{ .Values.environment }}
          volumeMounts:
            - mountPath: /usr/app/config/{{ .Values.environment }}.yaml
              name: config-pv-volume
              subPath: {{ .Values.environment }}.yaml
      volumes:
        - name: config-pv-volume
          emptyDir: {}
        - name: config-template-volume
          configMap:
            name: {{ .Chart.Name }}-config
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
