{{ if .Values.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-hpa-policy
  labels:
    team: {{ .Values.team }}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Chart.Name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{if .Values.hpa.metrics.cpu.enabled }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.metrics.cpu.targetAverageUtilization }}
  {{ end }}
  {{if .Values.hpa.metrics.memory.enabled }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.hpa.metrics.memory.targetAverageUtilization }}
  {{ end }}
{{ end }}