apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    team: {{ .Values.team }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http  
    port: {{ .Values.service.servicePort }}
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Chart.Name }}