name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    
    - name: Setup timezone
      run: sudo timedatectl set-timezone Asia/Kolkata

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: make clean build

    - name: Test
      run: make test
